### ISSUE TITLE
Parsing the filepath: regex vs custom parser

### ISSUE THREAD

**Issue by yjmantilla** [yjmantilla/sovabids#16]
So for parsing the filepath I originally had in mind something like this functionality from mp3tag:

![](https://user-images.githubusercontent.com/36543115/122836377-c15edd80-d2b7-11eb-8c95-7c5c294e112b.gif)

Basically the user inputs the pattern using percentages to delimitate the fields.

This is also possible with regex like this:

![](https://user-images.githubusercontent.com/36543115/123271805-cf367d80-d4c6-11eb-9e7f-75e55520a4da.png)
![](https://user-images.githubusercontent.com/36543115/123271996-f9883b00-d4c6-11eb-80aa-a584b02f1104.png)
![image](https://user-images.githubusercontent.com/36543115/123274553-3d7c3f80-d4c9-11eb-811c-5a11cd46a4eb.png)
![image](https://user-images.githubusercontent.com/36543115/123275789-402b6480-d4ca-11eb-9ca4-dd3b48c59656.png)

Each strategy has their strength and weaknesses:
- custom parser is more intuitive
- regex can parse more complex patterns, for example when the pattern is the number of characters instead of a separator
- custom parser cannot distinguish if there is no separator between the fields (ie in 'i1s001rest' it cannot separate 001 from rest)
- regex needs the user to input in another variable the fields (in order) as they are parsed on the string

As of now I'm supporting the custom parser but I think supporting regex will allow more flexibility for power users.

**Comment by stebo85** [comment]
I vote for using an already established technique like regex because people already know this and creating your own parser always looks easier than it is in the end

**Comment by yjmantilla** [comment]
@stebo85 I had already implemented the custom parser it works well enough, but the point of regex being the standard is good argument. I do find the custom parser more intuitive for non-technical users. 

I will try to implement the regex one and maybe put the whole parsing backend through regex, that is , translating the percentage notation of the custom parser to a regex pattern.  That way all is done through regex and the percentage notation is optional and only for non-technical users.

**Comment by yjmantilla** [comment]
closing this since it is already implemented in regex and the percentage notation translation to regex is also already implemented.
