### ISSUE TITLE
Change readme to something more simple

### ISSUE THREAD

**Issue by yjmantilla** [yjmantilla/sovabids#19]
So the readme is basically the gsoc proposal, it is quite verbose. We should do a more readable readme with maybe some basic usage.

Also leave the gsoc to another file (proposal.md)? It would be nice to keep it as history and as an initial blueprint of the project.

**Comment by civier** [comment]
Sure. Although I don't know if it's a priority at the moment. Do you know of people that accessing the project actively? I wonder if that would be the case before we make it public more widely.

**Comment by yjmantilla** [comment]
Not really, just the people I have mentioned the project to.

![image](https://user-images.githubusercontent.com/36543115/124033573-b85cc300-d9bf-11eb-832b-419549f478f8.png)

At most 14 people has accessed this repo hehe

**Comment by aswinnarayanan** [comment]
@yjmantilla For now, sounds like a good idea to move the GSOC proposal onto its own `about.md` and update the `README.md` with the basic instructions and also link to the about page.

**Comment by yjmantilla** [comment]
Closing this as it is done.
