### ISSUE TITLE
“Translation Rules” File Schema Deliverable

### ISSUE THREAD

**Issue by yjmantilla** [yjmantilla/sovabids#20]
@civier @stebo85 @aswinnarayanan @DavidjWhite33 

So according to the proposed timeline this first deliverable was for the 27th of June. 

I have already a first version of this deliverable in the form of a commented yaml. Nevertheless for it to be useful I'm considering making documentation for it along with typical use-case examples. The idea is to put that in an online documentation via mkdocs or sphinx ( I'm more in favour of mkdocs +plugins because it is easier, let me know if you have an opinion on this). 

Now, should I do something else for this to be considered "delivered" ? (maybe presenting it to you in a meeting or something like that?). 

Let me know.

Regarding the timeline I think we are good. A good portion of the backend is implemented as of now. I'm worried about the "Discover Rules" module but that one is not critical for the app (it can be used if the user does the rules himself).

I think even though we didn't made the GUI a goal of this GSOC, there is good chance for a basic GUI to be implemented within the timeline.

**Comment by civier** [comment]
@yjmantilla The idea of the agile development process we discussed is to have usable versions as we go along, and having a user (Dave) trying them out. So for me, it will be considered "delivered" when Dave can understand how to make a conversion using the commented yaml file (either following documentation that you'll write, or by you explaining to him directly).
Do you think you can write instructions that will be clear enough? If yes, let's go this path. Best if Dave can test it next week or the one after, in time for the first student evaluations.
If you rather set up a meeting to explain use, so we can do it in the same meeting when you'll tell us about BIDScoin architecture (in the week after next week). Give me your availability, and I'll set up something.
@DavidjWhite33, will you be available in the week starting 12th of July?

**Comment by yjmantilla** [comment]
>The idea of the agile development process we discussed is to have usable versions as we go along, and having a user (Dave) trying them out. So for me, it will be considered "delivered" when Dave can understand how to make a conversion using the commented yaml file (either following documentation that you'll write, or by you explaining to him directly).

Ahh, I understand. So whenever I have some worthy advances I guess the idea is to do a basic tutorial explaining it and passing it to Dave so that he plays with it a bit.

>Do you think you can write instructions that will be clear enough? If yes, let's go this path. Best if Dave can test it next week or the one after, in time for the first student evaluations.

Yes, I will try. I think it is nice having self-contained docs that explain the usage since in a way is like already advancing with the documentation. I put some effort on having quick datasets to test and to test them through github actions already with that idea in mind.

>Give me your availability, and I'll set up something.

Im pretty much available everyday, classes are still on hold... I guess the problem is the time offset. I think this is a good candidate:

![image](https://user-images.githubusercontent.com/36543115/124040730-15aa4180-d9cb-11eb-8bcb-c2b90b0f969b.png)

**Comment by DavidjWhite33** [comment]
Yes, I'll have some time in the week of the 12th to meet and discuss, 10am AEST is pretty good most days that week.

@yjmantilla if code and documentation are ready prior, then please let me know and I can give it a run in the meantime

**Comment by yjmantilla** [comment]
@DavidjWhite33 Sorry for the late reply, I was delving good into sphinx. I think the result is quite good.

For now I would be nice if you could take a look at : 

- The [intro of the documentation](https://sovabids.readthedocs.io/en/latest/README.html)
- The [rules file schema documentation](https://sovabids.readthedocs.io/en/latest/rules_schema.html) which is really verbose since is intended to fully document it.
- The [LEMON example](https://sovabids.readthedocs.io/en/latest/auto_examples/lemon_example.html) which suffered some changes as I split the old apply rules module (which did the conversion ) into a new apply rules modules that produces the mapping file and a convert_them module that performs the conversion; this since that was the targeted design. 

This last example has the problem of the paths being quite verbose as they are from the readthedocs machine. Locally they were more understandable. In any case these are details that can be improved down the line.

The bidscoin example is not yet in this new documentation because I'm still working on the sova2coin plugin, that is, updating it to the most recent bidscoin version and improving the architecture of the plugin.

Let me know how it goes.

**Comment by civier** [comment]
@yjmantilla @yjmantilla I schedule a meeting for next Tuesday (13/7) at 11:00am. Make sure to participate or let me know if not good.
See you then, Oren

**Comment by yjmantilla** [comment]
closing this as it is done
