### ISSUE TITLE
Getting hold of BrainVision and CNT datasets

### ISSUE THREAD

**Issue by civier** [yjmantilla/sovabids#4]
@TomEmotion Could you post here an example from your BrainVision dataset? If it cannot be made public, can you send it to Yorguin by email?
And so we will also have a BrainVision dataset with a different experimental design, which of our collaborators may have such datasets? Do you know who works with BrainVision?

**Comment by civier** [comment]
@yjmantilla You can also check these links for public datasets: https://github.com/openlists/ElectrophysiologyData#eeg-data
Maybe one of them is BrainVision

**Comment by yjmantilla** [comment]
Hi @civier and @TomEmotion

I actually for this [first test](https://github.com/yjmantilla/sovabids/blob/main/test_mne-bids.py) used the LEMON database which is on that list. I only downloaded 3 subjects for the test. 

I have never found an open .cnt dataset . Have you guys ever seen one?

**Comment by yjmantilla** [comment]
Closing this for now since seems like it is solved. Problem with the lemon dataset is that some fixes and decompressing need to be done before actually using them although this is cumbersomely fixed through the lemon scripts.
