### ISSUE TITLE
problem with using .cnt files 

### ISSUE THREAD

**Issue by neuro-sevas** [yjmantilla/sovabids#48]
In app.py eeg file extension is hard coded for vhdr files only

Line 176: "rules": {'non-bids':{'eeg_extension':'.vhdr'}},

**Comment by yjmantilla** [comment]
Also related to https://github.com/mne-tools/mne-bids/issues/922

**Comment by yjmantilla** [comment]
I finally was able to merge the PR in mne-bids related to this https://github.com/mne-tools/mne-bids/pull/924

**Comment by yjmantilla** [comment]
what's left is updating sovabids so that now it doesnt ask for my fork of mne-bids but rather the updated version
