### ISSUE TITLE
Give us permissions to label issues

### ISSUE THREAD

**Issue by civier** [yjmantilla/sovabids#7]
@yjmantilla Could you please change the Github permissions (I guess this is the problem), so all of us would be able to set the issues' assignees, labels, project, etc.? (the drop-downs on the right)
If it's not clear, we prefer to use Github as the main form of communications. Only if something cannot be posted publicly, we will use email. Is it ok with you and Brayan? (BTW, what is Brayan's Github nickname?)

Those are our nicknames:
Myself @civier
Steffen @stebo85
Tom @TomEmotion 
Aswin @aswinnarayanan 
Dave (EEG expert) @DavidjWhite33 
Will (MEG expert) @willw1

Also, do you know if there is a notion of groups in Github? i.e., can we indicate that an issue should be shared with a group of people? (that will make it easier to label issues that should be viewed by everybody)

**Comment by yjmantilla** [comment]
Hi @civier , just invited you all to the repo.

Brayan github is @leoBAHM

I think issues are public just like the repo, so they will be able to be seen by anyone.
